---
version: "3.7"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: make backend
    volumes:
      - ~/.bash_history:/root/.bash_history
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    stdin_open: true
    tty: true


volumes:
  pgdata: